Feature/16 19/post
Team-hangout/backend pull request #29
Opened 2023-05-02 10:50 UTC by vixloaze

## Merge Request Summary

- [ ] 기능 추가
- [ ] 버그 수정
- [ ] 코드 개선 (최적화)
- [ ] 기타

## Description

_상세 설명 (간단한 경우 생략 가능)_
게시글 수정, 삭제, 상세 조회, 조회 리스트 구현 완료했습니다.

---
## Issue Number 
- #Isuue Number
16~19
---
## Confirmed
- [ ] : reviewer Confirmed
- [ ] : @ohhonggi 
- [ ] : @Kim-Hye-Lin 
- [ ] : @BellYun 
---

- `@`를 통해 Reviewer를 지정해주세요
- 지정된 사용자는 확인 후 `Checkbox`에 체크해주세요
- Confirmed에 모두 체크된 경우 `Merge`를 진행합니다

2023-05-02 12:44 UTC, Kim-Hye-Lin reviewed
고생 정말 많으셨습니다
코드가 정말 깔끔하네요 ..! 많이 배웁니당 👍

2023-05-02 12:44 UTC, Kim-Hye-Lin commented on src/main/java/com/hangout/hangout/Post/application/PostService.java
> +    public List<PostListResponse> getPosts(PageRequest pageRequest) {
게시글 리스트 조회 시 게시글 상태가 공개인 게시글만 보이도록 조건 추가하면 좋을 것 같습니다 !

2023-05-02 12:44 UTC, Kim-Hye-Lin commented on src/main/java/com/hangout/hangout/Post/application/PostService.java
> +    public void createNewPost(PostRequest postRequest) {
변수 네이밍의 경우 
createNew+Entity로 갈지, createEntity 둘 중 한 방식으로 통일하면 좋을 것 같습니당!
내일 얘기해봐요:)

2023-05-02 12:52 UTC, Kim-Hye-Lin commented on src/main/java/com/hangout/hangout/Post/presentation/PostController.java
Controller에 이후에 Swagger 설명 추가하면 좋을 것 같습니당

2023-05-02 14:18 UTC, ohhonggi requested changes
Post 구현 양이 많으셨을텐데 고생하셨습니다! 👍👍

근데 현재 폴더 구조가 notion에 혜린님이 정리해주신 폴더구조랑 다른 것 같네요! [notion에 정리된 구조](https://www.notion.so/bbc1871430b84192be28e3786283bd84?pvs=4#2a185e7d59724b0e8cb71c2e4006cd57)는 domain/post 폴더 안에 controller, service, repository 등등으로 폴더 구조가 구성되어야 하는데, 지금 Post 폴더가 domain, global 폴더와 동일한 level에 있습니다!

그리고 추후 추가할 기능들을 주석으로 작성해 주셨는데, pr의 마지막에 **To-do** 등으로 정리하면 좋을 것 같아요!

2023-05-03 03:40 UTC, vixloaze commented on src/main/java/com/hangout/hangout/Post/application/PostService.java
> +    public List<PostListResponse> getPosts(PageRequest pageRequest) {
그 부분은 저도 인지하고 있는 부분이기에 좀 더 알아보고 고칠 예정입니다!

2023-05-03 03:42 UTC, vixloaze commented on src/main/resources/application.yml
> +      mode: always
이 부분은 https://www.notion.so/Database-sql-Reference-ef53493485664d6c8cea3790b1079523 요기에서 확인하시면 될 것 같습니다!

2023-05-03 03:48 UTC, vixloaze commented on src/main/java/com/hangout/hangout/Post/application/PostService.java
> +        Long newStatus = 1L;
확인했습니다! status 값을 부여하는 부분에서는 좀 더 생각해볼 필요가 있을 것 같네요... 수정하도록 하겠습니다!

2023-05-03 03:50 UTC, vixloaze commented on src/main/java/com/hangout/hangout/Post/PostMapper.java
> +public class PostMapper {
네 맞습니다. 해당 Mapper는 단순히 @builder 생성자들을 모아둔 클래스? 정도로 생각해주시면 좋을 것 같습니다

2023-05-03 12:02 UTC, merged